wasm macroquad v0.4

diff --git a/scripts/wasm-bindgen-macroquad b/scripts/wasm-bindgen-macroquad
--- a/scripts/wasm-bindgen-macroquad
+++ b/scripts/wasm-bindgen-macroquad
@@ -4,7 +4,7 @@ set -e
 
 HELP_STRING=$(
 	cat <<-END
-		usage: build_wasm.sh PROJECT_NAME
+		usage: build_wasm.sh PROJECT_NAME [--release]
 
 		Build script for combining a Macroquad project with wasm-bindgen,
 		allowing integration with the greater wasm-ecosystem.
@@ -16,8 +16,9 @@ HELP_STRING=$(
 			    1. Build as target 'wasm32-unknown-unknown'.
 			    2. Create the directory 'dist' if it doesn't already exist.
 			    3. Run wasm-bindgen with output into the 'dist' directory.
+		            - If the '--release' flag is provided, the build will be optimized for release.
 			    4. Apply patches to the output js file (detailed here: https://github.com/not-fl3/macroquad/issues/212#issuecomment-835276147).
-			        5. Generate coresponding 'index.html' file.
+			    5. Generate coresponding 'index.html' file.
 
 			Author: Tom Solberg <me@sbg.dev>
 			Edit: Nik codes <nik.code.things@gmail.com>
@@ -30,9 +31,9 @@ HELP_STRING=$(
 )
 
 die() {
-	echo >&2 "Error: $@"
-	echo >&2
 	echo >&2 "$HELP_STRING"
+	echo >&2
+	echo >&2 "Error: $*"
 	exit 1
 }
 
@@ -62,6 +63,7 @@ set -- "${POSITIONAL[@]}"
 [ $# -ne 1 ] && die "too many arguments provided"
 
 PROJECT_NAME=$1
+
 HTML=$(
 	cat <<-END
 		<html lang="en">
@@ -105,7 +107,6 @@ HTML=$(
 		        }
 		    </script>
 		    <div id="run-container" style="display: flex; justify-content: center; align-items: center; height: 100%; flex-direction: column;">
-		        <p>Game can't play audio unless a button has been clicked.</p>
 		        <button onclick="run()">Run Game</button>
 		    </div>
 		</body>
@@ -113,22 +114,25 @@ HTML=$(
 	END
 )
 
+TARGET_DIR="target/wasm32-unknown-unknown"
 # Build
 if [ -n "$RELEASE" ]; then
 	cargo build --release --target wasm32-unknown-unknown
+	TARGET_DIR="$TARGET_DIR/release"
 else
 	cargo build --target wasm32-unknown-unknown
+	TARGET_DIR="$TARGET_DIR/debug"
 fi
 
 # Generate bindgen outputs
 mkdir -p dist
-wasm-bindgen target/wasm32-unknown-unknown/debug/$PROJECT_NAME.wasm --out-dir dist --target web --no-typescript
+wasm-bindgen $TARGET_DIR/"$PROJECT_NAME".wasm --out-dir dist --target web --no-typescript
 
 # Shim to tie the thing together
-sed -i "s/import \* as __wbg_star0 from 'env';//" dist/$PROJECT_NAME.js
-sed -i "s/let wasm;/let wasm; export const set_wasm = (w) => wasm = w;/" dist/$PROJECT_NAME.js
-sed -i "s/imports\['env'\] = __wbg_star0;/return imports.wbg\;/" dist/$PROJECT_NAME.js
-sed -i "s/const imports = __wbg_get_imports();/return __wbg_get_imports();/" dist/$PROJECT_NAME.js
+sed -i "s/import \* as __wbg_star0 from 'env';//" dist/"$PROJECT_NAME".js
+sed -i "s/let wasm;/let wasm; export const set_wasm = (w) => wasm = w;/" dist/"$PROJECT_NAME".js
+sed -i "s/imports\['env'\] = __wbg_star0;/return imports.wbg\;/" dist/"$PROJECT_NAME".js
+sed -i "s/const imports = __wbg_get_imports();/return __wbg_get_imports();/" dist/"$PROJECT_NAME".js
 
 # Create index from the HTML variable
 echo "$HTML" >dist/index.html
